version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS= "fbecbaf139f465c6fc25719112d96f42de41034e"

  db:
    image: postgres
    environment:
      POSTGRES_DB: my_postgres_db      # Name of your database
      POSTGRES_USER: postgres          # Username for your database
      POSTGRES_PASSWORD: admin         # Password for your database user
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local  
